title: "Marilyn Stephens"
description: "Full-stack developer • Business owner turned technologist • Sales-driven problem solver"
theme: jekyll-theme-cayman
url: "https://Marilyn2015.github.io"
github_username: Marilyn2015
